import {firebaseConfig,isFirebaseConfigured} from "./firebase-config.js";
const $=s=>document.querySelector(s);const storeKey="soutalbekaa_demo_articles";let articles=JSON.parse(localStorage.getItem(storeKey)||"[]");let headerAd={};let firebase={};
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function initFirebase(){if(!isFirebaseConfigured)return false;try{const appMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js");const authMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js");const fireMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js");const storageMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-storage.js");const app=appMod.initializeApp(firebaseConfig);firebase={auth:authMod.getAuth(app),db:fireMod.getFirestore(app),storage:storageMod.getStorage(app),authMod,fireMod,storageMod};authMod.onAuthStateChanged(firebase.auth,user=>user?showDashboard(user):showLogin());return true}catch(e){$("#loginMessage").textContent="تعذّر الاتصال بالخدمة. تحقق من الإنترنت وحاول مجددًا.";return false}}
function showLogin(){$("#loginPage").hidden=false;$("#dashboard").hidden=true}async function showDashboard(user){$("#loginPage").hidden=true;$("#dashboard").hidden=false;$("#dashboardMessage").hidden=true;try{await loadArticles()}catch(error){console.warn(error);$("#dashboardMessage").textContent="تعذّر تحميل الأخبار لهذا الحساب. تواصل مع مسؤول الموقع.";$("#dashboardMessage").hidden=false}try{await loadHeaderAd()}catch(error){console.warn(error);renderAdPreview()}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();if(!isFirebaseConfigured){sessionStorage.setItem("demoAdmin","1");showDashboard();return}const button=e.submitter;button.disabled=true;button.textContent="جارٍ التحقق...";$("#loginMessage").textContent="";try{await firebase.authMod.signInWithEmailAndPassword(firebase.auth,$("#email").value.trim(),$("#password").value)}catch(err){console.warn("Login:",err.code,err.message);const messages={"auth/invalid-credential":"البريد الإلكتروني أو كلمة المرور غير صحيحة.","auth/user-disabled":"تم تعطيل حساب المدير.","auth/too-many-requests":"تم إيقاف المحاولات مؤقتاً. انتظر قليلاً ثم حاول مجدداً.","auth/network-request-failed":"تعذّر الاتصال بالخدمة. تحقق من الإنترنت وحاول مجدداً.","auth/operation-not-allowed":"تسجيل الدخول بالبريد غير متاح حاليًا.","auth/unauthorized-domain":"تسجيل الدخول غير متاح من هذا العنوان."};$("#loginMessage").textContent=messages[err.code]||"تعذّر تسجيل الدخول. حاول مجددًا.";}finally{button.disabled=false;button.textContent="دخول آمن"}};
$("#logoutButton").onclick=async()=>{if(isFirebaseConfigured)await firebase.authMod.signOut(firebase.auth);else{sessionStorage.removeItem("demoAdmin");showLogin()}};
async function loadArticles(){if(isFirebaseConfigured){const snap=await firebase.fireMod.getDocs(firebase.fireMod.query(firebase.fireMod.collection(firebase.db,"articles"),firebase.fireMod.orderBy("date","desc")));articles=snap.docs.map(d=>({id:d.id,...d.data()}))}renderRows()}
async function loadHeaderAd(){if(isFirebaseConfigured){const snap=await firebase.fireMod.getDoc(firebase.fireMod.doc(firebase.db,"ads","header"));headerAd=snap.exists()?snap.data():{}}renderAdPreview()}
function renderAdPreview(){const host=$("#adPreview");if(headerAd.image){host.innerHTML=`<img src="${safe(headerAd.image)}" alt="${safe(headerAd.name||"الإعلان العلوي")}"><div><strong>${safe(headerAd.name||"إعلان بدون اسم")}</strong><span class="status ${headerAd.active?"":"draft"}">${headerAd.active?"نشط":"متوقف"}</span></div>`}else host.innerHTML="<span>لا يوجد إعلان محفوظ حاليًا</span>"}
function renderRows(list=articles){$("#articleRows").innerHTML=list.length?list.map(a=>`<tr><td><div class="title-cell"><img src="${safe(a.image||"assets/logo.jpeg")}" alt=""><strong>${safe(a.title)}</strong></div></td><td>${safe(a.category)}</td><td><span class="status ${a.status==="draft"?"draft":""}">${a.status==="draft"?"مسودة":"منشور"}</span></td><td>${safe(a.date||"")}</td><td class="row-actions"><button class="edit" data-edit="${a.id}">تعديل</button><button class="delete" data-delete="${a.id}">حذف</button></td></tr>`).join(""):`<tr><td colspan="5">لا توجد أخبار بعد. اضغط «إضافة خبر جديد» للبدء.</td></tr>`;$("#totalCount").textContent=articles.length;$("#publishedCount").textContent=articles.filter(a=>a.status!=="draft").length;$("#draftCount").textContent=articles.filter(a=>a.status==="draft").length;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteArticle(b.dataset.delete))}
function openEditor(id){$("#articleForm").reset();$("#articleId").value="";$("#editorTitle").textContent="إضافة خبر جديد";$("#mainImageHint").textContent="تُضغط الصورة تلقائيًا لتحسين سرعة الموقع.";if(id){const a=articles.find(x=>String(x.id)===String(id));if(a){$("#editorTitle").textContent="تعديل الخبر";["title","category","status","excerpt","body","author","authorRole","videoUrl"].forEach(k=>$("#"+k).value=a[k]||"");$("#mainImageHint").textContent=a.image?"توجد صورة محفوظة. اختر صورة جديدة فقط إذا أردت استبدالها.":"لا توجد صورة حالية؛ اختر صورة للخبر.";$("#breaking").checked=!!a.breaking;$("#featured").checked=!!a.featured;$("#articleId").value=a.id}}$("#editorDialog").showModal()}
$("#newArticle").onclick=()=>openEditor();$("#closeEditor").onclick=$("#cancelEditor").onclick=()=>$("#editorDialog").close();
$("#editAd").onclick=()=>{$("#adForm").reset();$("#adName").value=headerAd.name||"";$("#adLink").value=headerAd.link||"";$("#adActive").checked=!!headerAd.active;$("#adFormMessage").textContent="";$("#adDialog").showModal()};$("#closeAdEditor").onclick=$("#cancelAdEditor").onclick=()=>$("#adDialog").close();
async function compressImage(file){if(!file)return null;if(!file.type.startsWith("image/"))throw new Error("الملف المختار ليس صورة.");if(file.size>15*1024*1024)throw new Error("حجم الصورة الأصلية أكبر من 15MB.");const bitmap=await createImageBitmap(file);const max=1600;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",.82));if(!blob)throw new Error("تعذّر ضغط الصورة.");if(blob.size>=5*1024*1024)throw new Error("الصورة أكبر من 5MB حتى بعد الضغط.");return blob}
async function uploadImage(file,folder){if(!file)return"";const blob=await compressImage(file);const imageRef=firebase.storageMod.ref(firebase.storage,`${folder}/${Date.now()}-${crypto.randomUUID()}.webp`);await firebase.storageMod.uploadBytes(imageRef,blob,{contentType:"image/webp"});return firebase.storageMod.getDownloadURL(imageRef)}
$("#adForm").onsubmit=async e=>{e.preventDefault();const button=$("#saveAdButton");button.disabled=true;button.textContent="جارٍ الحفظ...";$("#adFormMessage").textContent="";try{const file=$("#adImage").files[0];const image=file?await uploadImage(file,"ads"):(headerAd.image||"");const active=$("#adActive").checked;if(active&&!image)throw new Error("اختر صورة للإعلان قبل تشغيله.");headerAd={name:$("#adName").value.trim(),link:$("#adLink").value.trim(),image,active,updatedAt:new Date().toISOString()};await firebase.fireMod.setDoc(firebase.fireMod.doc(firebase.db,"ads","header"),headerAd);renderAdPreview();$("#adDialog").close()}catch(err){$("#adFormMessage").textContent="تعذّر حفظ الإعلان: "+err.message}finally{button.disabled=false;button.textContent="حفظ الإعلان"}};
$("#articleForm").onsubmit=async e=>{e.preventDefault();const button=$("#saveButton");button.disabled=true;button.textContent="جارٍ ضغط الصور ورفعها...";$("#formMessage").textContent="";try{const id=$("#articleId").value;const old=articles.find(a=>String(a.id)===String(id));const mainFile=$("#mainImage").files[0];if(!mainFile&&!old?.image)throw new Error("اختر صورة رئيسية للخبر.");const galleryFiles=[...$("#galleryImages").files];if(galleryFiles.length>10)throw new Error("الحد الأقصى للألبوم هو 10 صور.");const image=mainFile?await uploadImage(mainFile,"articles"):(old?.image||"");const authorFile=$("#authorImage").files[0];const authorImage=authorFile?await uploadImage(authorFile,"authors"):(old?.authorImage||"");const uploadedGallery=await Promise.all(galleryFiles.map(file=>uploadImage(file,"galleries")));const gallery=uploadedGallery.length?uploadedGallery:(old?.gallery||[]);const article={title:$("#title").value.trim(),category:$("#category").value,status:$("#status").value,excerpt:$("#excerpt").value.trim(),body:$("#body").value.trim(),author:$("#author").value.trim(),authorRole:$("#authorRole").value.trim(),authorImage,videoUrl:$("#videoUrl").value.trim(),breaking:$("#breaking").checked,featured:$("#featured").checked,image,gallery,date:old?.date||new Date().toISOString().slice(0,10),views:old?.views||0};if(isFirebaseConfigured){if(id)await firebase.fireMod.updateDoc(firebase.fireMod.doc(firebase.db,"articles",id),article);else await firebase.fireMod.addDoc(firebase.fireMod.collection(firebase.db,"articles"),article)}else{if(id){articles=articles.map(a=>String(a.id)===String(id)?{...a,...article}:a)}else articles.unshift({id:crypto.randomUUID(),...article});localStorage.setItem(storeKey,JSON.stringify(articles))}await loadArticles();$("#editorDialog").close()}catch(err){$("#formMessage").textContent="حدث خطأ أثناء الحفظ: "+err.message}finally{button.disabled=false;button.textContent="حفظ الخبر"}};
async function deleteArticle(id){if(!confirm("هل تريد حذف هذا الخبر نهائياً؟"))return;if(isFirebaseConfigured)await firebase.fireMod.deleteDoc(firebase.fireMod.doc(firebase.db,"articles",id));else{articles=articles.filter(a=>String(a.id)!==String(id));localStorage.setItem(storeKey,JSON.stringify(articles))}await loadArticles()}
$("#adminSearch").oninput=e=>{const q=e.target.value.trim();renderRows(articles.filter(a=>(a.title+" "+a.category+" "+a.author).includes(q)))};
if(await initFirebase()){/* auth observer controls screen */}else if(sessionStorage.getItem("demoAdmin"))showDashboard();
