import {firebaseConfig,isFirebaseConfigured} from "./firebase-config.js";
const $=s=>document.querySelector(s);const storeKey="soutalbekaa_demo_articles";let articles=JSON.parse(localStorage.getItem(storeKey)||"[]");let firebase={};
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function initFirebase(){if(!isFirebaseConfigured)return false;try{const appMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js");const authMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js");const fireMod=await import("https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js");const app=appMod.initializeApp(firebaseConfig);firebase={auth:authMod.getAuth(app),db:fireMod.getFirestore(app),authMod,fireMod};authMod.onAuthStateChanged(firebase.auth,user=>user?showDashboard(user):showLogin());return true}catch(e){$("#loginMessage").textContent="تعذّر الاتصال بـ Firebase. تحقق من الإعدادات.";return false}}
function showLogin(){$("#loginPage").hidden=false;$("#dashboard").hidden=true}async function showDashboard(user){$("#loginPage").hidden=true;$("#dashboard").hidden=false;$("#adminIdentity").textContent=`UID: ${user.uid}`;$("#dashboardMessage").hidden=true;try{await loadArticles()}catch(error){console.warn(error);$("#dashboardMessage").textContent=`رفض Firestore الوصول لهذا الحساب. تأكد أن UID الظاهر هنا موجود في القواعد المنشورة: ${user.uid}`;$("#dashboardMessage").hidden=false}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();if(!isFirebaseConfigured){sessionStorage.setItem("demoAdmin","1");showDashboard();return}const button=e.submitter;button.disabled=true;button.textContent="جارٍ التحقق...";$("#loginMessage").textContent="";try{await firebase.authMod.signInWithEmailAndPassword(firebase.auth,$("#email").value.trim(),$("#password").value)}catch(err){console.warn("Firebase Auth:",err.code,err.message);const messages={"auth/invalid-credential":"البريد الإلكتروني أو كلمة المرور غير صحيحة. تأكد من استخدام بيانات الحساب الموجود في Firebase Authentication.","auth/user-disabled":"تم تعطيل حساب المدير من Firebase.","auth/too-many-requests":"تم إيقاف المحاولات مؤقتاً. انتظر قليلاً ثم حاول مجدداً.","auth/network-request-failed":"تعذّر الاتصال بـ Firebase. تحقق من الإنترنت وحاول مجدداً.","auth/operation-not-allowed":"طريقة Email/Password غير مفعّلة في Firebase Authentication.","auth/unauthorized-domain":"نطاق GitHub Pages غير مضاف إلى Authorized domains في Firebase."};$("#loginMessage").textContent=messages[err.code]||`تعذّر تسجيل الدخول (${err.code||"خطأ غير معروف"}).`;}finally{button.disabled=false;button.textContent="دخول آمن"}};
$("#logoutButton").onclick=async()=>{if(isFirebaseConfigured)await firebase.authMod.signOut(firebase.auth);else{sessionStorage.removeItem("demoAdmin");showLogin()}};
async function loadArticles(){if(isFirebaseConfigured){const snap=await firebase.fireMod.getDocs(firebase.fireMod.query(firebase.fireMod.collection(firebase.db,"articles"),firebase.fireMod.orderBy("date","desc")));articles=snap.docs.map(d=>({id:d.id,...d.data()}))}renderRows()}
function renderRows(list=articles){$("#articleRows").innerHTML=list.length?list.map(a=>`<tr><td><div class="title-cell"><img src="${safe(a.image||"assets/logo.jpeg")}" alt=""><strong>${safe(a.title)}</strong></div></td><td>${safe(a.category)}</td><td><span class="status ${a.status==="draft"?"draft":""}">${a.status==="draft"?"مسودة":"منشور"}</span></td><td>${safe(a.date||"")}</td><td class="row-actions"><button class="edit" data-edit="${a.id}">تعديل</button><button class="delete" data-delete="${a.id}">حذف</button></td></tr>`).join(""):`<tr><td colspan="5">لا توجد أخبار بعد. اضغط «إضافة خبر جديد» للبدء.</td></tr>`;$("#totalCount").textContent=articles.length;$("#publishedCount").textContent=articles.filter(a=>a.status!=="draft").length;$("#draftCount").textContent=articles.filter(a=>a.status==="draft").length;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteArticle(b.dataset.delete))}
function openEditor(id){$("#articleForm").reset();$("#articleId").value="";$("#editorTitle").textContent="إضافة خبر جديد";if(id){const a=articles.find(x=>String(x.id)===String(id));if(a){$("#editorTitle").textContent="تعديل الخبر";["title","category","status","excerpt","body","author","authorRole","authorImage","videoUrl"].forEach(k=>$("#"+k).value=a[k]||"");$("#mainImage").value=a.image||"";$("#galleryImages").value=(a.gallery||[]).join("\n");$("#breaking").checked=!!a.breaking;$("#featured").checked=!!a.featured;$("#articleId").value=a.id}}$("#editorDialog").showModal()}
$("#newArticle").onclick=()=>openEditor();$("#closeEditor").onclick=$("#cancelEditor").onclick=()=>$("#editorDialog").close();
$("#articleForm").onsubmit=async e=>{e.preventDefault();const button=$("#saveButton");button.disabled=true;button.textContent="جارٍ الحفظ...";try{const id=$("#articleId").value;const old=articles.find(a=>String(a.id)===String(id));const gallery=$("#galleryImages").value.split(/\r?\n/).map(url=>url.trim()).filter(Boolean);const article={title:$("#title").value.trim(),category:$("#category").value,status:$("#status").value,excerpt:$("#excerpt").value.trim(),body:$("#body").value.trim(),author:$("#author").value.trim(),authorRole:$("#authorRole").value.trim(),authorImage:$("#authorImage").value.trim(),videoUrl:$("#videoUrl").value.trim(),breaking:$("#breaking").checked,featured:$("#featured").checked,image:$("#mainImage").value.trim(),gallery,date:old?.date||new Date().toISOString().slice(0,10),views:old?.views||0};if(isFirebaseConfigured){if(id)await firebase.fireMod.updateDoc(firebase.fireMod.doc(firebase.db,"articles",id),article);else await firebase.fireMod.addDoc(firebase.fireMod.collection(firebase.db,"articles"),article)}else{if(id){articles=articles.map(a=>String(a.id)===String(id)?{...a,...article}:a)}else articles.unshift({id:crypto.randomUUID(),...article});localStorage.setItem(storeKey,JSON.stringify(articles))}await loadArticles();$("#editorDialog").close()}catch(err){$("#formMessage").textContent="حدث خطأ أثناء الحفظ: "+err.message}finally{button.disabled=false;button.textContent="حفظ الخبر"}};
async function deleteArticle(id){if(!confirm("هل تريد حذف هذا الخبر نهائياً؟"))return;if(isFirebaseConfigured)await firebase.fireMod.deleteDoc(firebase.fireMod.doc(firebase.db,"articles",id));else{articles=articles.filter(a=>String(a.id)!==String(id));localStorage.setItem(storeKey,JSON.stringify(articles))}await loadArticles()}
$("#adminSearch").oninput=e=>{const q=e.target.value.trim();renderRows(articles.filter(a=>(a.title+" "+a.category+" "+a.author).includes(q)))};
if(await initFirebase()){/* auth observer controls screen */}else if(sessionStorage.getItem("demoAdmin"))showDashboard();
